@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZTMuY29tIiwiZXhwIjoxNzY0MDc5MDYwLCJwdWJfaWQiOiI5MGViZTlkYy00YWE0LTQ4YWUtYjYwNy05YzY3MTRjMGI1OTMiLCJyb2xlIjoidXNlciIsInVzZXJfaWQiOjJ9.6S9gBeHYVQHV1Qx5q25Ojg09QooyUf7SUL0am0SETD4
### Register
POST {{baseUrl}}/v1/auth/register
Content-Type: application/json

{
    "name": "John Doe 3",
    "email": "john@example3.com",
    "password": "password",
    "role": "user"
}

### Login
POST {{baseUrl}}/v1/auth/login
Content-Type: application/json

{    
    "email": "john@example3.com",
    "password": "password"
}

### Get User
GET {{baseUrl}}/api/v1/users/5206c6e2-2112-4f0b-bc62-72097e5cc33b
Authorization: Bearer {{accessToken}}

### Get User Pagination
GET {{baseUrl}}/api/v1/users/page?limit=2&page=1
Authorization: Bearer {{accessToken}}

### Update User
PUT {{baseUrl}}/api/v1/users/5206c6e2-2112-4f0b-bc62-72097e5cc33b
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{    
    "name": "John Doe Update"
}

### Get User Pagination
DELETE {{baseUrl}}/api/v1/users/2
Authorization: Bearer {{accessToken}}

### Create Board
POST {{baseUrl}}/api/v1/boards
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Board 5",
    "description": "Deskripsi board 5",
    "due_date": "2025-12-31T15:04:00+07:00"
}

### Update Board
PUT {{baseUrl}}/api/v1/boards/83d8d4db-cb10-419a-afa5-bdefc7d9230c
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Board 4 Update 2",
    "description": "Deskripsi board 4 update 2",
    "due_date": "2025-12-31T15:04:00+07:00"
}
