@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG40QGV4YW1wbGUuY29tIiwiZXhwIjoxNzY0NzcyNDgyLCJwdWJfaWQiOiI0ODdmOGRkZi1iZTU3LTQzMTItOGY4ZS04OWY5ODgyYTllZDMiLCJyb2xlIjoidXNlciIsInVzZXJfaWQiOjN9.ED2kDUdf2UiwRiHPxSueCjrW07jgvIXkj-3pr3C3Cl4
### Register
POST {{baseUrl}}/v1/auth/register
Content-Type: application/json

{
    "name": "John Doe 6",
    "email": "john6@example.com",
    "password": "password",
    "role": "user"
}

### Login
POST {{baseUrl}}/v1/auth/login
Content-Type: application/json

{    
    "email": "john4@example.com",
    "password": "password"
}

### Get User
GET {{baseUrl}}/api/v1/users/5206c6e2-2112-4f0b-bc62-72097e5cc33b
Authorization: Bearer {{accessToken}}

### Get User Pagination
GET {{baseUrl}}/api/v1/users/page?limit=2&page=1
Authorization: Bearer {{accessToken}}

### Update User
PUT {{baseUrl}}/api/v1/users/5206c6e2-2112-4f0b-bc62-72097e5cc33b
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{    
    "name": "John Doe Update"
}

### Get User Pagination
DELETE {{baseUrl}}/api/v1/users/2
Authorization: Bearer {{accessToken}}

### Create Board
POST {{baseUrl}}/api/v1/boards
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Board 4",
    "description": "Deskripsi board 4",
    "due_date": "2025-12-31T15:04:00+07:00"
}

### Update Board
PUT {{baseUrl}}/api/v1/boards/83d8d4db-cb10-419a-afa5-bdefc7d9230c
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Board 4 Update 2",
    "description": "Deskripsi board 4 update 2",
    "due_date": "2025-12-31T15:04:00+07:00"
}

### Add Board Members
POST {{baseUrl}}/api/v1/boards/c07cc85b-06cd-43e5-8b87-a2c39e98852b/members
Content-Type: application/json
Authorization: Bearer {{accessToken}}

[
    "0ec9b470-45c8-4daa-9778-7a1592e00e0a",
    "6350ec60-8118-47ca-95dd-39f4d9371f7a",
    "cc32fcc1-f42c-47e7-aa12-f448b05d062b"
]

### Remove Board Members
DELETE {{baseUrl}}/api/v1/boards/c07cc85b-06cd-43e5-8b87-a2c39e98852b/members
Content-Type: application/json
Authorization: Bearer {{accessToken}}

[
    "0ec9b470-45c8-4daa-9778-7a1592e00e0a"
]

### Get My Board Pagination
GET {{baseUrl}}/api/v1/boards/my/page?limit=2&page=1
Authorization: Bearer {{accessToken}}

### Create List
POST {{baseUrl}}/api/v1/lists
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "List 1",
    "board_public_id": "c07cc85b-06cd-43e5-8b87-a2c39e98852b"
}
